kind: pipeline
type: docker
name: hello

steps:
- name: greeting
  image: alpine
  commands:
  - echo hello
  - echo world
  
trigger:
  branch:
  - master
  
---
kind: pipeline
type: docker
name: default

steps:
- name: test
  image: node
  commands:
  - npm install

trigger:
  event:
  - promote
  target:
  - production
